version: '3.8'

services:
  mysql:
    image: mysql:8.0.19
    container_name: mysql-proyecto
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: hola123
    ports:
      - 33062:3306
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
      - mysql-data:/var/lib/mysql
          
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.2
    container_name: phpmyadmin-proyecto
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
    ports:
      - 81:80
  backend:
    container_name: "backend-proyecto"
    build:
      context: docker
      dockerfile: Dockerfile
    command: sh -c "npm install && npm run start"
    user: 1000:1000
    working_dir: /app
    ports:
      - 3001:3001
    depends_on:
      - mysql-proyecto
    volumes:
      - .:/app

volumes:
  mysql-data: