version: '3.8'

services:
  mysql:
    image: mysql:8.0.19
    container_name: mysql-proyecto
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    ports:
      - ${DB_PORT_HOST}:3306
    volumes:
      - ./database/db.sql:/docker-entrypoint-initdb.d/db.sql
      - mysql-data:/var/lib/mysql
          
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.2
    container_name: phpmyadmin-proyecto
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
    ports:
      - ${PHPMYADMIN_PORT_HOST}:80
    depends_on:
      - mysql

  backend:
    container_name: backend-proyecto
    build:
      context: docker
      dockerfile: Dockerfile
    command: sh -c "wait-for-it mysql:3306 -t 300 && npm install && npm run start"
    user: 1000:1000
    working_dir: /app
    ports:
      - ${PORT}:3001
    depends_on:
      - mysql
    volumes:
      - .:/app
    environment:
      - APP_SECRET=${APP_SECRET}
      - TOKEN_EXPIRATION=60d
      - DB_HOST=mysql
      - DB_NAME=ExpedientesProfesores
      - DB_USER=root
      - DB_PASS=${DB_PASS}

volumes:
  mysql-data:
